service: dynamodels-tests

provider:
  name: aws
  runtime: nodejs10.x
  stage: test

plugins:
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - test
    start:
      port: ${env:LOCAL_DYNAMODB_PORT, 8000}
      inMemory: true
